services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dudes
      - POSTGRES_USER=dudes
      - POSTGRES_DB=dudes

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://dudes:dudes@postgres:5432/dudes?schema=public
    ports:
      - 3000:3000
      - 4200:4200
      - 4300:4300
    depends_on:
      - postgres
    volumes:
      - .:/app
      - node-modules:/app/node_modules

volumes:
  postgres-data:
    name: dudes-postgres
  node-modules:
    name: dudes-node-modules
